$ 255
Weiter mit Tastendruck!
$ 99
Vergangenheitswerte der
ausgewählten Variablen:
(Tastendruck -> weiter)
-----------------------
Periode
$ 1
Der Wert lag nicht im erlaubten Bereich.
Die Grenzen sind : # bis #.
$ 2
Der Wert lag nicht im erlaubten Bereich.
Die Grenzen sind : # bis #.
Kommastellen sind nicht erlaubt.
$ 3
Das eingegebene Zeichen
war nicht korrekt.
Erlaubte Zeichen sind: >#<
$ 4
Ihre Eingabe entsprach
nicht dem Zahlenformat.
$ 8
       Pardon!
Für dieses Feld gibt
es keine Hilfestellung.
$ 12
Ja: Es werden ALLE Entscheidungsdaten
    für alle Gruppen und Perioden genullt!
$ 13
Ja: Es werden die von TATA gelieferten
    Standard-Spielleitungsdaten für
    alle Perioden übern
ommen!
$ 14
Der hier eingegebene Text erscheint
als Titel in den Menüs und Berichten.

$ 36
Laufwerk # NICHT bereit.
Datenträger einlegen!
$ 37
Ausgabe erfolgt auf die
ASCII-Textdatei "#".
Abbruch möglich mit ESC
$ 50
Lese Entscheidungen P
Schreibe Ergebnisse P
Initialisiere Daten P
$ 70
Phasenberechnung durchgeführt!
$ 71
Zeitpunkt # berechnet!
$ 72
Sie dürfen das Formular erst
verlassen, wenn die letzte Woche
der Phase (Woche #) berechnet wurde!
$ 100
Wollen Sie die Daten aus der
Planungsphase übernehmen?
$ 101
Fehler beim Kopieren!
#
Fehlernummer #: Zieldiskette voll?
$ 102
         Achtung!
Keine einzige Datei gefunden!
     Bitte prüfen Sie!
$ 103
Pfad # nicht gefunden,
Vorgang wird abgebrochen!
$ 104
Transfer beendet!
$ 105
Achtung, Achtung!

Sie sind dabei, Ihre erarbeiteten
Planungsdaten zu löschen!
Wollen Sie das wirklich?
$ 106
Keine Daten!
$ 107
Wollen Sie die Datenversion #
wirklich überschreiben?
$ 108
Bitte geben Sie zuerst die Nummer
des betroffenen Vorgangs ein!
$ 109
Dieses Modul braucht
eine 32-bit-Umgebung!
$ 111
Anlegen der Datei:
#
(Teilnehmerberichte für Unternehmen #)
$ 112
Anlegen der Datei:
#
(Teilnehmerberichte für alle Unternehmen)
$ 113
Anlegen der Datei:
#
(Seminarleitungsberichte)
$ 114
Datentransfer:
stellen Sie sicher, dass der eingestellte Pfad
" # " für Unternehmen #
verfügbar ist!
$ 115
Datentransfer: der eingestellte Pfad
" # " für Unternehmen # ist nicht verfügbar!
(Abbruch = nächstes Unternehmen)
$ 116
Der Bildschirm ist nicht optimal eingestellt!
Empfohlene Mindestauflösung: # Pixel!
$ 117
#:
Damit schließen Sie die Gruppensitzung
der laufenden Phase endgültig ab!
Wollen Sie das wirklich?
$ 118
Sie habe die nächste Projektphase noch nicht freigegeben!
Wollen Sie das Programm trotzdem beenden?
$ 120
#:

Damit überschreiben Sie Ihre aktuellen Daten und übernehmen die
vom Seminarleiter für die nächste Simulation bereitgestellten Daten!
Sind Sie sicher?
$ 121
#:

Damit übertragen Sie Ihre aktuellen Daten auf 
den Datenträger für den Seminarleiter!
Sind Sie sicher?
$ 198
Phase freigeben:
Sind Sie sicher, dass Sie die nächste Phase
mit Planungsstand "#" berechnen wollen?
$ 199
unterschiedliche Phasenstände der Gruppen!
$ 200
#:

Sind Sie sicher?

