$ 255
Press any key to continue.
$ 99
Past values of actual variable:
(Press any key to continue.)
-------------------------------
Period
$ 1
The value was not within
the permitted range.
The range is: # to #.
$ 2
The value was not within the permitted range.
The range is: # to #.
Figures after the decimal point are not permitted.
$ 3
The character entered
was not correct.
Permitted characters are: >#<
$ 4
Your entry did not correspond
to the proper format.
$ 8
       Sorry!
No help available for
this field.
$ 12
Yes: ALL decisions of ALL groups
     and ALL periods will be deleted!
$ 13
Yes: TATA data for period 0 will
     be used for all periods.
$ 14
The text you enter here will appear
in the title of all reports.
$ 36
The file path # is not ready!
Please insert data medium.
$ 37
Print out ASCII-file "#".
$ 50
Reading decisions. P
Writing results. P
Initialising data. P
$ 70
Phase was calculated
$ 71
Period # was calculated!
$ 72
You must not leave this form
until the last week of the phase 
(week #) has been calculated!
$ 100
Do you want to save your data?
$ 101
Error while copying!
#
Error number #: Target disk full?
$ 102
         Warning!
No files found,
 Please check.
$ 103
File path # not found,
Process aborted.
$ 104
Data transfer completed.
$ 105
Warning!

You are going to delete
your decision data!
Are you sure?
$ 106
No Data!
$ 107
Do you really want to
overwrite the game version #?
$ 108
Please insert number of activity first!
$ 109
This module requires a
32 bit environment!
$ 111
Creating file:
#
(participants' report for company #)
$ 112
Creating file:
#
(participants' report for all companies)
$ 113
Creating file:
#
(Instructor's reports)
$ 114
Data transfer:
Please make sure that the file path
" # " for company #
is available!
$ 115
Data transfer: the given file path
" # " for company # is not available!
(Click "Cancel" to try next company)
$ 116
Please check you screen resolution.
Best at: # Pixel!
$ 117
#:
This will finish your session! 
It's not possible to make further 
decisions for the current phase.
Do you really want to carry on?
$ 118
You haven't released your next phase! 
Do you really want to exit?
$ 120
#:
You overwrite your current data. 
Are you sure? 

$ 121
#:

You write your current data on the data medium!
Are you sure? 
$ 198
Release phase:
Are you sure that you want to calculate the next
phase using planning scenario "#"?
$ 199
different actual phase standings in groups!
$ 200
#:

Are you sure?
